import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem", md: "2rem", lg: "2.5rem", xl: "3rem" },
      screens: { sm: "640px", md: "768px", lg: "1024px", xl: "1280px", "2xl": "1400px" },
    },
    extend: {
      spacing: {
        '0': 'var(--space-0)', 'px': 'var(--space-px)', '0.5': 'var(--space-0-5)',
        '1': 'var(--space-1)', '1.5': 'var(--space-1-5)', '2': 'var(--space-2)',
        '2.5': 'var(--space-2-5)', '3': 'var(--space-3)', '3.5': 'var(--space-3-5)',
        '4': 'var(--space-4)', '5': 'var(--space-5)', '6': 'var(--space-6)',
        '7': 'var(--space-7)', '8': 'var(--space-8)', '9': 'var(--space-9)',
        '10': 'var(--space-10)', '11': 'var(--space-11)', '12': 'var(--space-12)',
        '14': 'var(--space-14)', '16': 'var(--space-16)', '18': '4.5rem',
        '20': 'var(--space-20)', '22': '5.5rem', '24': 'var(--space-24)',
        '30': '7.5rem', '88': '22rem', '112': '28rem', '128': '32rem',
        'section': 'var(--space-section)', 'page': 'var(--space-page)',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        info: { DEFAULT: "hsl(var(--info))", foreground: "hsl(var(--info-foreground))" },
        celebration: { DEFAULT: "hsl(var(--celebration))", foreground: "hsl(var(--celebration-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        role: {
          owner: "hsl(var(--role-owner))", manager: "hsl(var(--role-manager))",
          buyer: "hsl(var(--role-buyer))", contact: "hsl(var(--role-contact))",
        },
        surface: {
          0: "hsl(var(--surface-0))", 1: "hsl(var(--surface-1))",
          2: "hsl(var(--surface-2))", 3: "hsl(var(--surface-3))", 4: "hsl(var(--surface-4))",
        },
        entity: {
          contact: "hsl(var(--entity-contact))", company: "hsl(var(--entity-company))",
          interaction: "hsl(var(--entity-interaction))", insight: "hsl(var(--entity-insight))",
        },
        "ring-destructive": "hsl(var(--ring-destructive))",
        "ring-success": "hsl(var(--ring-success))",
        "ring-warning": "hsl(var(--ring-warning))",
      },
      borderRadius: {
        lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)",
        '2xl': '1rem', '3xl': '1.5rem',
      },
      boxShadow: {
        'soft': 'var(--shadow-sm)', 'medium': 'var(--shadow-md)',
        'strong': 'var(--shadow-lg)', 'intense': 'var(--shadow-xl)',
        'inner-sm': 'inset 0 1px 2px 0 rgb(0 0 0 / 0.05)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-out": { from: { opacity: "1" }, to: { opacity: "0" } },
        "slide-in-up": { from: { transform: "translateY(8px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
        "scale-in": { from: { transform: "scale(0.97)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "pulse-soft": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.7" } },
        "skeleton": { "0%": { backgroundColor: "hsl(var(--muted))" }, "50%": { backgroundColor: "hsl(var(--muted) / 0.5)" }, "100%": { backgroundColor: "hsl(var(--muted))" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "slide-in-up": "slide-in-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
        "shimmer": "shimmer 2s linear infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "skeleton": "skeleton 1.5s ease-in-out infinite",
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'swift': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      zIndex: {
        'dropdown': '100', 'sticky': '200', 'fixed': '300', 'overlay': '400',
        'modal-backdrop': '500', 'modal': '600', 'popover': '700',
        'tooltip': '800', 'toast': '900', 'max': '9999',
      },
      minHeight: { 'touch': '44px', 'touch-comfortable': '48px' },
      minWidth: { 'touch': '44px', 'touch-comfortable': '48px' },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
